### PR TITLE
Remove duplicate CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by ekohl** [comment]
I wonder if we should set this via modulesync:
```yaml
CONTRIBUTING.md:
  delete: true
```

**Comment by dhoppe** [comment]
@ekohl I had the same idea, but I did not want to inflate ```modulesync``` unnecessarily. Also, I already covered almost all modules.

**Comment by ekohl** [comment]
You could also use modulesync to do it all but not commit. I've used `msync update --offline` to do the patches and then some shell loops around it to submit PRs.

**Comment by dhoppe** [comment]
@ekohl That would definitely have been the more intelligent solution. ;)

**Comment by ekohl** [comment]
A typical loop I'd use is:
```bash
for mod in modules/*/puppet-* ; do
  ( cd $mod && git add CONTRIBUTING.md && git co -b remove-duplicate-contributing && git commit -m '[skip ci] Remove duplicate CONTRIBUING.md' && git push --quiet $REMOTE HEAD && hub pull-request -m 'Remove duplicate CONTRIBUTING.md' )
done
```

**Pull request merged**
