### PR TITLE
Fix variable clobbering [typo]

### PR DESCRIPTION
**Pull request by JohnHolmesII**
```
Server Error: Evaluation Error: Unknown variable: 'config_file_v6_content'. (file:
/etc/puppetlabs/code/environments/production/modules/bird/manifests/init.pp, line: 242, column: 15)
```

IPv6 via epp must not be very popular, or this likely would have been uncovered sooner!

### CODE REVIEW

**Review by smortex — COMMENTED** [review]
Makes sense, but this prove the test suite does not check the correct behavior of these parameters. Can you add some tests that prove it actually works so that we can avoid regression in the future?

**Comment by JohnHolmesII** [comment]
Looking at the hilaritude of errors, I'm assuming the Arch testing is incomplete.

Also, at what point might we see another release on the forge? Getting a bit long in the tooth, and of course I'd love to have my own patch ASAP, I'm not in love with pointing at commits.

**Review by smortex — APPROVED** [review]
LGTM!

**Comment by smortex** [comment]
Yes, we can ignore the ArchLinux failure at this point.  We do not have a process to determine when we do a new release, but anyone can trigger the process by [creating a release PR](https://voxpupuli.org/docs/releasing_version/). Feel free to trigger a new release :-)

**Pull request merged**
